/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ch_fhnw_prcpp_u02_Matrix */

#ifndef _Included_ch_fhnw_prcpp_u02_Matrix
#define _Included_ch_fhnw_prcpp_u02_Matrix
#ifdef __cplusplus
extern "C" {
#endif
void multiply(jdouble * a, jdouble * b, jdouble * r, jint x, jint y, jint k);
/*
 * Class:     ch_fhnw_prcpp_u02_Matrix
 * Method:    multiplyC
 * Signature: ([D[D[DIII)V
 */
JNIEXPORT void JNICALL Java_ch_fhnw_prcpp_u02_Matrix_multiplyC
  (JNIEnv *, jclass, jdoubleArray, jdoubleArray, jdoubleArray, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
